### ISSUE TITLE
tar_plan example in README.Rmd

### ISSUE THREAD

**Issue by eheinzen** [wlandau/tarchetypes#16]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/tarchetypes/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problem you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

In README.Rmd, you reference [`tar_plan()`](https://github.com/wlandau/tarchetypes/blob/0df0d0d3a1d5a755b593928ab61d6a4504417cc7/README.Rmd#L120), but the accompanying example doesn't use `tar_plan()`; rather, it uses `tar_pipeline()`.  I think that's a mistake?

I think you could also change the first target to a `tar_file()`, if you wanted to?

Thanks for a great package, and all the contributed talks lately!

**Comment by wlandau** [comment]
Thanks for the nice suggestions. Now implemented.
