### ISSUE TITLE
Support pattern in `tar_map()`

### ISSUE THREAD

**Issue by psychelzh** [wlandau/tarchetypes#24]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/tarchetypes/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Currently, `tar_map()` is a helper function to build static branches, but it does not have a `pattern` argument. I think this could be added in order for a better combination of static and dynamic branches.

**Comment by wlandau** [comment]
I do not think there is a need. `tar_map()` accepts fully-formed target objects with `pattern`s of their own, and static branching modifies those patterns as needed. Users should set `pattern` beforehand on a target-by-target basis.

``` r
library(targets)
tar_script({
  library(tarchetypes)
  templates <- list(
    tar_target(x, f(a)),
    tar_target(y, f(x), pattern = map(x)),
    tar_target(z, g(y), pattern = map(y))
  )
  targets <- tar_map(values = list(a = c(1, 2)), templates)
  tar_pipeline(targets)
})

tar_manifest()
#> # A tibble: 6 x 3
#>   name  command pattern 
#>   <chr> <chr>   <chr>   
#> 1 z_1   g(y_1)  map(y_1)
#> 2 z_2   g(y_2)  map(y_2)
#> 3 y_1   f(x_1)  map(x_1)
#> 4 y_2   f(x_2)  map(x_2)
#> 5 x_1   f(1)    <NA>    
#> 6 x_2   f(2)    <NA>

tar_visnetwork(targets_only = TRUE)
```

![](https://i.imgur.com/oNlodoR.png)

<sup>Created on 2020-12-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by psychelzh** [comment]
Thanks, that is very clean. But here I have a case that the pattern of `tar_map()` have to be dynamic.

Specifically, I have data from many psychological tests, each of which has to be preprocessed by a different function. This makes my pipeline be based on data and function simultaneously. Functions are not treated as something to be branched over dynamically in `targets`, so I build static branches over all of these functions. However, the data have to be dynamic because they can not be fetched easily, and thus a target in the pipeline is required. And then the `tar_map()` is preferably branched over this target, a dynamic one.

So I am looking forward this pattern supported in `tar_map()`, although I can use `tar_target_raw()` to build iteratively by myself. Maybe there are some other better methods?

**Comment by wlandau** [comment]
I suggest a different way to express the pipeline, either with static branching to split the data before preprocessing or dynamic branching to map over a list of functions. Sketch of the latter:

```r
tar_pipeline(
  tar_target(
    dataset,
    download_dataset() %>%
      dplyr::group_by(...),
      targets::tar_group(),
    iteration = "group" 
  ),
  tar_target(
    functions,
    create_function_list_from_dataset(dataset),
    iteration = "list"
  ),
  tar_target(
    preprocessed,
    functions(dataset),
    pattern = map(functions, dataset)
  )
)
```

`pattern` in `tar_map()` would be incompatible with the design of `targets` and `tarchetypes` and would risk enabling suboptimal usage habits.

**Comment by psychelzh** [comment]
Maybe the challenge here is to track the changes of functions. I have ever tried this method, and there is no way to make it work if there is a dynamic branch for functions.

**Comment by wlandau** [comment]
The function list should always rerun (quick) but only the affected branches should rerun after that (see evidence below).

``` r
library(targets)

tar_script({
  options(crayon.enabled = FALSE)
  f <- function() {
    c(f = "f_current")
  }
  g <- function() {
    c(g = "g_old")
  }
  tar_pipeline(
    tar_target(
      functions,
      list(f = f, g = g),
      iteration = "list"
    ),
    tar_target(
      output,
      functions(),
      pattern = map(functions)
    )
  )
})

tar_make()
#> * run target functions
#> * run branch output_e1755eb6
#> * run branch output_51320a50

tar_read(output)
#>           f           g 
#> "f_current"     "g_old"

tar_script({
  options(crayon.enabled = FALSE)
  f <- function() {
    c(f = "f_current")
  }
  g <- function() {
    c(g = "g_new")
  }
  tar_pipeline(
    tar_target(
      functions,
      list(f = f, g = g),
      iteration = "list"
    ),
    tar_target(
      output,
      functions(),
      pattern = map(functions)
    )
  )
})

tar_make()
#> * run target functions
#> v skip branch output_e1755eb6
#> * run branch output_6dbb0c9e

tar_read(output)
#>           f           g 
#> "f_current"     "g_new"
```

<sup>Created on 2020-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

One note: functions have fickle internals that change the first few times they are called, which changes the hash. This was a problem in `drake` when users returned functions from targets: https://github.com/ropensci/drake/issues/345. Because of the improvements in `targets`, I think this is unlikely to affect you (unless you call `tar_make(callr_function = NULL)` and manually run the functions repeatedly in the same R session) but I have not spent much time exploring it personally.

**Comment by psychelzh** [comment]
Thank you very much! Creating a target of function lists works as expect. This is a much cleaner way of doing this.

**Comment by psychelzh** [comment]
Thank you very much! I have learnt what you mean, maybe I need to refactor it a little. Later I will post my solutions, which uses `tar_target_raw()` instead.

**Comment by wlandau** [comment]
> I just have no idea how to create the functions list from a configuration file which stores the function names as characters.

You can use tidy evaluation to insert symbols into a target's command. That should allow you to start from a character vector.

``` r
library(targets)
tar_script({
  library(rlang)
  library(targets)
  fns <- c(a = "a", b = "b")
  list(
    tar_target(functions, list(!!!syms(fns)))
  )
})

tar_manifest()
#> # A tibble: 1 x 3
#>   name      command            pattern
#>   <chr>     <chr>              <chr>  
#> 1 functions list(a = a, b = b) <NA>
```

<sup>Created on 2021-03-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

> I have tried getFromNamespace() or get(), which worked but it will always rerun if the function is from a package and the package updates. 

To track functions from a package and the inner nested functions they call, list the package name in  `imports` option as [described here](https://books.ropensci.org/targets/practices.html#workflows-as-r-packages).

**Comment by psychelzh** [comment]
Thank you very much for your response, and sorry for late feedback. This method requires `fns` is an object that is not dynamically generated. So it is not so compatible with the previous suggestion of `create_function_list_from_dataset()`.

> I suggest a different way to express the pipeline, either with static branching to split the data before preprocessing or dynamic branching to map over a list of functions. Sketch of the latter:
> 
> ```r
> tar_pipeline(
>   tar_target(
>     dataset,
>     download_dataset() %>%
>       dplyr::group_by(...),
>       targets::tar_group(),
>     iteration = "group" 
>   ),
>   tar_target(
>     functions,
>     create_function_list_from_dataset(dataset),
>     iteration = "list"
>   ),
>   tar_target(
>     preprocessed,
>     functions(dataset),
>     pattern = map(functions, dataset)
>   )
> )
> ```
> 
> `pattern` in `tar_map()` would be incompatible with the design of `targets` and `tarchetypes`, and it would risk enabling suboptimal usage habits.

**Comment by wlandau** [comment]
If that's the case, then we are back to static branching over functions and dynamically branching over data, which is the better option anyway when it can be done.

``` r
library(targets)
tar_script({
  options(tidyverse.quiet = TRUE)
  library(rlang)
  library(targets)
  library(tarchetypes)
  library(tidyverse)
  values <- tribble(
    ~f,   ~g,   ~name,
    "f1", "g1", "function_set1",
    "f2", "g2", "function_set2",
  ) %>%
    mutate(f = syms(f), g = syms(g))
  tar_map(
    values = values,
    names = name,
    tar_target(x, f()),
    tar_target(y, g(x), pattern = map(x))
  )
})

tar_manifest()
#> # A tibble: 4 x 3
#>   name            command             pattern             
#>   <chr>           <chr>               <chr>               
#> 1 x_function_set1 f1()                <NA>                
#> 2 x_function_set2 f2()                <NA>                
#> 3 y_function_set1 g1(x_function_set1) map(x_function_set1)
#> 4 y_function_set2 g2(x_function_set2) map(x_function_set2)

tar_visnetwork(targets_only = TRUE)
```

![](https://i.imgur.com/vDozC5u.png)

<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by psychelzh** [comment]
Thank you for your quick response. I am just thinking about it the same way as your last post, so there should be some trade-off in this case. I will try using this method.

**Comment by psychelzh** [comment]
The final version I used is as follows:

https://github.com/psychelzh/tarflow.iquizoo/blob/35b558315a62adc4d3f7393f0d97d4c1834c7de0/inst/templates/_targets_indices.R#L18-L27
