### ISSUE TITLE
RStudio addins

### ISSUE THREAD

**Issue by wlandau** [wlandau/tarchetypes#7]
## Prework

* [x] I understand and agree to `tarchetypes`' [code of conduct](https://github.com/wlandau/tarchetypes/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `tarchetypes`' [contributing guidelines](https://github.com/wlandau/tarchetypes/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I think this is a better place for addins than {targets}, but as with #7, a well-defined scope is key. (Maybe all we need is a better package name and a couple adjustments to the docs?)

Some initial ideas:

* Load target at cursor.
* Write `tar_target()` at cursor.
* Run the pipeline.
* Visualize the graph.
* Show outdated targets.
* Run `tar_progress()`.

cc @MilesMcBain

**Comment by wlandau-lilly** [comment]
Moving to https://github.com/wlandau/targets/issues/137 so [`tarchetypes`](https://github.com/wlandau/tarchetypes) can focus on archetypes of targets and pipelines. The scope and goals of both packages seems clearer this way.
